# This file was generated by GoReleaser. DO NOT EDIT.
cask "baseproof" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "cb62900df8c7837502fde809742efc98c2c9f75c84c999c844ba2ea0feac3c65"
      url "https://github.com/baseproof/cli/releases/download/v#{version}/baseproof_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b776927866a9dec376f92ce0bf6273c230d33a0d42d88f70609b86c8ae652131"
      url "https://github.com/baseproof/cli/releases/download/v#{version}/baseproof_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "faba13d7b1b16c176f697739063e7a0e859e9280f41bd0ee1d8cb57f19851f37"
      url "https://github.com/baseproof/cli/releases/download/v#{version}/baseproof_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d411d4598a3d0bddfeb001de560d63d87486d640a55f2eac169b29a7a81e51dd"
      url "https://github.com/baseproof/cli/releases/download/v#{version}/baseproof_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baseproof"
  desc "Unified client for a baseproof network"
  homepage "https://github.com/baseproof/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baseproof"
  manpage "man/man1/baseproof-completion-bash.1"
  manpage "man/man1/baseproof-completion-fish.1"
  manpage "man/man1/baseproof-completion-powershell.1"
  manpage "man/man1/baseproof-completion-zsh.1"
  manpage "man/man1/baseproof-completion.1"
  manpage "man/man1/baseproof-config-list.1"
  manpage "man/man1/baseproof-config-set.1"
  manpage "man/man1/baseproof-config.1"
  manpage "man/man1/baseproof-docs.1"
  manpage "man/man1/baseproof-info.1"
  manpage "man/man1/baseproof-load.1"
  manpage "man/man1/baseproof-network-add.1"
  manpage "man/man1/baseproof-network-list.1"
  manpage "man/man1/baseproof-network-show.1"
  manpage "man/man1/baseproof-network-use.1"
  manpage "man/man1/baseproof-network.1"
  manpage "man/man1/baseproof-proof.1"
  manpage "man/man1/baseproof-submit.1"
  manpage "man/man1/baseproof-verify.1"
  manpage "man/man1/baseproof-witnesses.1"
  manpage "man/man1/baseproof.1"
  bash_completion "completions/baseproof.bash"
  fish_completion "completions/baseproof.fish"
  zsh_completion "completions/_baseproof"

  # No zap stanza required

end
