# This file was generated by GoReleaser. DO NOT EDIT.
cask "baseproof" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "7968c34d8b12f01aeeb98d83108962cc392580487f3b581e68cad12cb9623314"
      url "https://github.com/baseproof/cli/releases/download/v#{version}/baseproof_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9f24d19d873fdadbb61873448d6fdf3209f63c45207db1df25c75e051e6b7e5"
      url "https://github.com/baseproof/cli/releases/download/v#{version}/baseproof_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c438b0386070169ee151fcb1390323b89b8f8c06dc5ca30c861e31fc2865987b"
      url "https://github.com/baseproof/cli/releases/download/v#{version}/baseproof_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0887681c54754e568ab724bf624d7fde3d962db5d84318ec7bd648cebde61a9b"
      url "https://github.com/baseproof/cli/releases/download/v#{version}/baseproof_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baseproof"
  desc "Unified client for a baseproof network"
  homepage "https://github.com/baseproof/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baseproof"
  manpage "man/man1/baseproof-completion-bash.1"
  manpage "man/man1/baseproof-completion-fish.1"
  manpage "man/man1/baseproof-completion-powershell.1"
  manpage "man/man1/baseproof-completion-zsh.1"
  manpage "man/man1/baseproof-completion.1"
  manpage "man/man1/baseproof-config-list.1"
  manpage "man/man1/baseproof-config-set.1"
  manpage "man/man1/baseproof-config.1"
  manpage "man/man1/baseproof-docs.1"
  manpage "man/man1/baseproof-info.1"
  manpage "man/man1/baseproof-load.1"
  manpage "man/man1/baseproof-network-add.1"
  manpage "man/man1/baseproof-network-list.1"
  manpage "man/man1/baseproof-network-show.1"
  manpage "man/man1/baseproof-network-use.1"
  manpage "man/man1/baseproof-network.1"
  manpage "man/man1/baseproof-proof.1"
  manpage "man/man1/baseproof-submit.1"
  manpage "man/man1/baseproof-verify.1"
  manpage "man/man1/baseproof-witnesses.1"
  manpage "man/man1/baseproof.1"
  bash_completion "completions/baseproof.bash"
  fish_completion "completions/baseproof.fish"
  zsh_completion "completions/_baseproof"

  # No zap stanza required

end
